instance:
  clientUrl: https://your-domain.com  # Set this correctly from the start
  persistentUrl: https://purl.org

repository:
  type: 5
  blazegraph:
    url: http://blazegraph:8080/blazegraph

security:
  jwt:
    token:
      secret-key:  [Add your 256 JWT Token]

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/fdp

metadataProperties:
  language: http://id.loc.gov/vocabulary/iso639-1/en
  license: http://rdflicense.appspot.com/rdflicense/cc-by-nc-nd3.0
  accessRightsDescription: This resource has no access restriction
  publisherURI: [Add your Organization URL]
  publisherName: "Name of Organization/Institution"